# Generated by Django 3.2.9 on 2021-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcalorie',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
