# Generated by Django 3.2.9 on 2021-11-15 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_foodcalorie_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcalorie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 8, 40, 28, 333459, tzinfo=utc)),
        ),
    ]
