# Generated by Django 3.2.9 on 2021-11-15 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_alter_foodcalorie_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcalorie',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
